services:
  db:
    image: postgres:16
    container_name: nota_db
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: nota_db        
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: nota_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: nota_web
    volumes:
      - processing_data:/processing
      - nota_tmp:/tmp/nota
      - static_volume:/app/staticfiles  # Add this for Caddy to access static files
    ports:
      - "8001:8000"  # Changed from 8000 to 8001 to avoid conflict with soundleaf
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
      - DEBUG=${DEBUG:-0}
    entrypoint: ["/app/entrypoint.prod.sh"]

  celery:
    build: .
    container_name: nota_celery
    volumes:
      - processing_data:/processing
      - nota_tmp:/tmp/nota
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      - DJANGO_ENV=production
      - DEBUG=${DEBUG:-0}
    entrypoint: ["/app/entrypoint.celery.sh"]
    command: ["celery", "-A", "nota_db", "worker", "--loglevel=info"]

  caddy:
    image: caddy:2.8
    container_name: nota_caddy
    ports:
      - "8080:80"   # Different port to avoid conflict with soundleaf
      - "8443:443"  # Different port to avoid conflict with soundleaf
    volumes:
      - /etc/caddy/Caddyfile.notadb:/etc/caddy/Caddyfile
      - /etc/caddy/notadb.crt:/etc/caddy/notadb.crt
      - /etc/caddy/notadb.key:/etc/caddy/notadb.key
      - static_volume:/app/staticfiles
      - caddy_data_nota:/data
      - caddy_config_nota:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  processing_data:
  nota_tmp:
  static_volume:  # Add this new volume for static files
  caddy_data_nota:  # Add this for Caddy data
  caddy_config_nota:  # Add this for Caddy config
