services:
  db:
    image: postgres:16
    container_name: nota_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: nota_db        
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: nota_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
    build: .
    container_name: nota_celery
    command: celery -A nota_db worker --loglevel=info
    volumes:
      - ./files:/app/files
      - ./nota_db:/app/nota_db
      - ./entrypoint.web.sh:/app/entrypoint.web.sh
      - ./entrypoint.celery.sh:/app/entrypoint.celery.sh
      - ./entrypoint.prod.sh:/app/entrypoint.prod.sh
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - nota_tmp:/tmp/nota
      - processing_data:/processing
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DEBUG=1
    entrypoint: ["/app/entrypoint.celery.sh"]

  web:
    build: .
    container_name: nota_web
    volumes:
      - ./files:/app/files
      - ./nota_db:/app/nota_db
      - ./entrypoint.web.sh:/app/entrypoint.web.sh
      - ./entrypoint.celery.sh:/app/entrypoint.celery.sh
      - ./entrypoint.prod.sh:/app/entrypoint.prod.sh
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - nota_tmp:/tmp/nota
      - processing_data:/processing
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["/app/entrypoint.web.sh"]

volumes:
  postgres_data:
  redis_data:
  processing_data:
  nota_tmp: