# Generated by Django 5.1.2 on 2024-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdffile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'PDF File', 'verbose_name_plural': 'PDF Files'},
        ),
        migrations.AddField(
            model_name='pdffile',
            name='composer',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
