# Generated by Django 5.1.2 on 2024-11-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_pdffile_options_pdffile_composer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='description',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
