# Generated by Django 5.2.1 on 2025-05-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_pdffile_processed_pdffile_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='processed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
