# Generated by Django 5.2.1 on 2025-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_pdffile_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='midi_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='musicxml_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
