# Generated by Django 5.2.1 on 2025-06-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_pdffile_midi_url_pdffile_musicxml_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
