# Generated by Django 5.2.1 on 2025-07-02 13:55

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_pdffile_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='file',
            field=models.FileField(blank=True, storage=files.models.PDFFileStorage(), upload_to=''),
        ),
    ]
